# Fires off the raw frigate/events MQTT topic rather than the frigate
# integration's own triggers, so it needs no entity plumbing per camera.
- alias: Security_Frigate_Notifications_Person
  description: ''
  trigger:
  - platform: mqtt
    topic: frigate/events
    payload: new
    value_template: '{{ value_json.type }}'
  condition:
  - '{{ trigger.payload_json[''after''][''label''] == ''person'' }}'
  action:
  - service: notify.mobile_app_justins_iphone
    data:
      message: A {{trigger.payload_json["after"]["label"]}} was detected in {{trigger.payload_json["after"]["camera"]}}.
      data:
        image: https://home.justbuchanan.com/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/snapshot.jpg
        tag: '{{trigger.payload_json["after"]["id"]}}'
        when: '{{trigger.payload_json["after"]["start_time"]|int}}'
        data:
          url: https://cctv.justbuchanan.com/cameras/{{trigger.payload_json["after"]["camera"]}}
  mode: single
  id: 442395df58154198b99c5a2496dc3502
