#! /bin/sh

bspc config border_width        2
bspc config window_gap         10

bspc config split_ratio         0.5
#bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d "web" "social" "media" "rj dev" "bm dev" "sys"

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off



bspc config focused_border_color "#0000FF"


cd /home/justbuchanan/.config/bspwm/panel; ./panel dzen2 &




