#! /bin/sh

bspc config border_width        2
bspc config window_gap         10

bspc config split_ratio         0.5
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d "web" "social" "media" "RJ:1" "RJ:2" "BM:1" "BM:2" "sys"

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a spotify desktop=^3



bspc config focused_border_color "#3399ff"


cd /home/justbuchanan/.config/bspwm/panel; exec ./panel &

