[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.shell]
command = "shfmt"
options = ["-i", "2", "-sr", "-s"]
includes = ["*.sh"]

[formatter.shellcheck]
command = "shellcheck"
includes = ["*.sh"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.md", "*.yaml", "*.yml"]
