#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%a %b %d, %Y %H:%M' > "$PANEL_FIFO" &


COLOR_ICON="#3399FF"

# WiFi
INTERFACE=wlp2s0
while true; do
    QUAL=`iwconfig $INTERFACE | grep 'Link Quality=' | awk '{gsub(/[=/]/," "); print $3}'`
    MAX=`iwconfig $INTERFACE | grep 'Link Quality=' | awk '{gsub(/[=/]/," "); print $4}'`
    PERC=`echo $QUAL*100/$MAX | bc`
    SSID="$(essid -w $INTERFACE)"
    echo -e "N%{T2}%{F$COLOR_ICON}\uf1eb%{F-}%{T1} $PERC% $SSID" > "$PANEL_FIFO"
    sleep 1
done &

# battery
while true; do
    BAT=`acpi -b | awk '{gsub(/%,/,""); print $4}' | sed 's/%//g'`
    STATUS=`acpi -b | awk '{gsub(/,/,""); print $3}'`
    echo -e "B%{T2}%{F$COLOR_ICON}\uf0e7%{F-}%{T1} $BAT% $STATUS" > "$PANEL_FIFO"
    sleep 1
done &

# volume
while true; do
    VOL=$(amixer get Master | tail -n 1 | cut -d '[' -f 2 | cut -d ']' -f 1)
    echo -e "V%{T2}%{F$COLOR_ICON}\uf028%{F-}%{T1} $VOL" > "$PANEL_FIFO"
done &



source ./panel_colors

cat "$PANEL_FIFO" | panel_bar | lemonbar -g x$PANEL_HEIGHT -f "$PANEL_FONT_FAMILY" -fFontAwesome -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &
# cat "$PANEL_FIFO" | panel_bar | lemonbar -g x$PANEL_HEIGHT -fFontAwesome "$PANEL_FONT_FAMILY" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &

wait
