#!/usr/bin/env python3

import i3ipc

"""
Query i3 for current workspace numbers, then create a new workspace with the
smallest unused number. For example, if workspaces 1, 2, and 4 are open, this
script will open a new workspace at 3.
"""
i3 = i3ipc.Connection()
workspace_nums = sorted([ws['num'] for ws in i3.get_workspaces()])
n = 1
while n == workspace_nums[n-1]:
    n += 1
i3.command('workspace %d' % n)
